version: '3.1'

services:
  secretsantabot:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ../../migrations:/migrations
    environment:
      POSTGRES_USER: secretsantabot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secretsantabot
      PGDATA: /var/lib/postgresql/data/pgdata
