run:
  deadline: 5m
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  stylecheck:
    go: "1.21"
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  staticcheck:
    go: "1.21"
    checks: ["all"]
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 55
    statements: 30
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    enable-all: true
  golint:
    min-confidence: 0.9
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/truewebber/secretsantabot
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/truewebber/secretsantabot) # Custom section: groups all imports with the specified Prefix.
      - blank
      - dot
    skip-generated: true
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
    tab-width: 1
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - whyNoLint
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 64

linters:
  enable-all: true
  disable:
    # not helpful linters
    - varnamelen
    - exhaustruct
    - ireturn
    - tagliatelle
    - depguard
    # deprecated linters
    - nosnakecase
    - interfacer
    - scopelint
    - golint
    - structcheck
    - varcheck
    - ifshort
    - deadcode
    - maligned
    - exhaustivestruct

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        # Table tests are ok to have a lot of lines inside a function
        - funlen

        # Tests could have long lines due to provided test data
        - lll

        # Auto-generated tests may have cuddled assignments
        - wsl

        # Auto-generated tests may be using reflect.DeepEqual
        - govet

        # Tests may have small functions with defined errors instead of global vars
        - goerr113

        # Auto-generated table tests contain a context.Context field
        - containedctx

        # Test might to be bulky
        - maintidx

        # Tests or cases could be similar
        - dupl

    # For white-box testing
    - path: _internal_test\.go
      linters:
        - testpackage
