name: Go

on:
  push:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: print version
        run: golangci-lint --version

      - name: lint
        run: golangci-lint -v run -c .golangci.yml ./...

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -race -v ./...
